#!/bin/bash
export IMAGE=$(sed -n '1p' /tmp/.auth)
export TAG=$(sed -n '2p' /tmp/.auth)
export PASS=$(sed -n '3p' /tmp/.auth)

docker login -u nguyendangkhoa2k4 -p $PASS

cd ~/maven

# Xóa container cũ trước khi recreate
docker-compose down

# Chạy lại
docker-compose up -d
